<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>CHAMS Reports</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h1 {
            margin: 0;
            color: #2c3e50;
        }

        .header p {
            margin: 5px 0 0;
            color: #7f8c8d;
        }

        .section {
            margin-bottom: 30px;
        }

        .section h2 {
            background-color: #34495e;
            color: white;
            padding: 8px;
            margin: 0 0 10px;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .summary-cards {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
        }

        .card {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
            flex: 1;
        }

        .card h3 {
            margin: 0;
            color: #2c3e50;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ccc;
            font-size: 10px;
            color: #7f8c8d;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>CHAMS - Clinical Health Appointment Management System</h1>
        <p>Report Generated: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Generated by: {{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</p>
    </div>

    <div class="summary-cards">
        <div class="card">
            <h3>{{ $completedCount }}</h3>
            <p>Completed Appointments (All Time)</p>
        </div>
        <div class="card">
            <h3>{{ $completedThisMonth }}</h3>
            <p>Completed (This Month)</p>
        </div>
        <div class="card">
            <h3>{{ $cancelledCount }}</h3>
            <p>Cancelled Appointments</p>
        </div>
    </div>

    <div class="section">
        <h2>Staff Activity Report</h2>
        <table>
            <thead>
                <tr>
                    <th>Staff Name</th>
                    <th>Appointments Handled</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($staffActivity as $staff)
                    <tr>
                        <td>{{ $staff->name }}</td>
                        <td>{{ $staff->assigned_appointments_count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Top Clients (by visits)</h2>
        <table>
            <thead>
                <tr>
                    <th>Client Name</th>
                    <th>Total Visits</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($clientVisits as $client)
                    <tr>
                        <td>{{ $client->full_name }}</td>
                        <td>{{ $client->appointments_count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Weekly Summary (Last 7 Days)</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Appointments</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($weeklyAppointments as $day)
                    <tr>
                        <td>{{ $day['date'] }}</td>
                        <td>{{ $day['count'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>CHAMS - Clinical Health Appointment Management System</p>
        <p>This report is system-generated and confidential.</p>
    </div>
</body>

</html>
